### PR TITLE
Major code restructure

### PR DESCRIPTION
**Pull request by sarajcev**
Major code restructuring with unified features engineering (single function), variable renaming and redundant code removal.

### CODE REVIEW

**Comment by sarajcev** [comment]
I have made some major changes to the code base. @NilsJakob could you review these changes and see if this looks fine by you? If you agree that this is the way we should proceed, could you merge this PR? The `engineer_features` function has been created for a single-step ahead predictions. We should decide if we want it to be more general and make provisions for the multi-step predictions.

**Comment by sarajcev** [comment]
A combination of `dictionary` and a two-element `tuple` is used for hard-coding the local holidays. I think that a combination of the unordered hash table (with `pandas` assignment by `.loc`) and the immutability of tuples as its values is a good combination for what we need.

**Review by NilsJakob — APPROVED** [review]
These new changes in restructure-code is good with me, and i agree it is the way the proceed - and now merged with master

**Comment by NilsJakob** [comment]
I am not deleting branch now at this moment.

**Pull request merged**
